root = "."
tmp_dir = "tmp"

[build]
    cmd = "templ generate && go build -o ./tmp/main cmd/main.go"
    bin = "./tmp/main"
    delay = 1000
    exclude_dir = ["assets", "tmp", "vendor", "node_modules", "frontend", "e2e"]
    include_ext = ["go", "tpl", "tmpl", "templ", "html"]
    exclude_regex = ["_test\\.go", "_templ\\.go"]
    kill_delay = 10

[proxy]
# Enable live-reloading on the browser.
    enabled = true
    proxy_port = 8090
    app_port = 8080