services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ENVIRONMENT=development
      - ENV=development
      - DOMAIN=localhost
      - DB_PATH=/data/database.db
    volumes:
      - ".:/app"  # Mount source code for live reloading
      - "/app/tmp"  # Exclude tmp directory created by Air
      - "../files/sqlite:/data"  # Keep SQLite data
    networks:
      - dev-network
    entrypoint: ["/entrypoint.sh"]

  frontend:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "5173:5173"  # Vite's default port
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevents local node_modules from mounting over container's
    command: sh -c "npm install && npm run dev -- --host"  # --host allows external connections
    environment:
      - NODE_ENV=development
    networks:
      - dev-network

networks:
  dev-network:
    name: dev-network