services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080
    environment:
      - PORT=8080
      - ENVIRONMENT=production
      - DOMAIN=${DOMAIN}
      - ENV=production
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 15s   # Added to give application time to start
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.gochat_service.loadbalancer.server.port=8080"
      - "traefik.http.routers.gochat.service=gochat_service"
      - "traefik.http.routers.gochat.entrypoints=websecure"
      - "traefik.http.routers.gochat.tls.certResolver=letsencrypt"
      - "traefik.http.routers.gochat.rule=Host(`${DOMAIN}`)"
    deploy:
      labels:
        - "traefik.http.services.gochat_service.loadbalancer.passhostheader=true"
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
networks:
  dokploy-network:
    external: true