services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SENTRY_DSN=your-sentry-dsn
      - ENVIRONMENT=production
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      # Add a unique service name
      - "traefik.http.services.gochat_service.loadbalancer.server.port=3000"
      # Update the router to explicitly use this service
      - "traefik.http.routers.gochat.service=gochat_service"
      - "traefik.http.routers.gochat.entrypoints=websecure"
      - "traefik.http.routers.gochat.tls.certResolver=letsencrypt"
      - "traefik.http.routers.gochat.rule=Host(`app.torgon.io`)"

networks:
  dokploy-network:
    external: true