// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package schema

import (
	"database/sql"
)

type Account struct {
	ID        string
	Name      string
	Createdat string
	Updatedat string
}

type User struct {
	ID         string
	Name       string
	Email      string
	Account    string
	Externalid sql.NullString
	Createdat  string
	Updatedat  string
}
