// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package schema

import (
	"database/sql"
)

type Account struct {
	ID        int64
	Name      sql.NullString
	Createdat sql.NullString
	Updatedat sql.NullString
}

type User struct {
	ID         int64
	Name       sql.NullString
	Email      sql.NullString
	Account    int64
	Externalid sql.NullString
	Createdat  sql.NullString
	Updatedat  sql.NullString
}
